# Generated by Django 4.0.4 on 2022-07-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_article_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='images/trades/'),
        ),
    ]
