# Generated by Django 4.0.6 on 2022-07-18 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_alter_article_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'اخبار', 'verbose_name_plural': 'اخبار'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'منابع', 'verbose_name_plural': 'منابع'},
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='data_added',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='images//%Y/%m/%d/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='News.source', verbose_name='منبع'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', ' بایگانی ها '), ('p', 'منتشر شده'), ('w', 'پیش نویس')], max_length=1, verbose_name='وضعیت انتشار'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=250, verbose_name='تیتر'),
        ),
        migrations.AlterField(
            model_name='article',
            name='writer',
            field=models.CharField(max_length=150, verbose_name='نویسنده'),
        ),
    ]
